/* -----------------------------------------------------------------Ĺ-----------
 *
 * Author:      Kjell Swedin
 * Description: Interface code for python bindings to FuelbedValues objects.
 * Date:        2/18/2016
 *
 ----------------------------------------------------------------------------- */
 
#if 0
# - Use to generate from a list of the enum types

eFUELBED_NUMBER,
eFUELBED_NAME,
eFUELBED_DESCRIPTION,
.
.
.

import sys

def process(filename):
    with open(filename, 'r') as infile:
        count = 0
        for line in infile:
            line = line.strip()
            line = line.rstrip(',')
            if len(line):
                print('.value("{}", FBTypes::{})'.format(line, line))
                count += 1
        print(count)

if len(sys.argv) > 1:
    process(sys.argv[1])

#endif
 
#include "pybind11.h"
#include "stl.h"
#include "fuelbed_values.h"

namespace py = pybind11;

PYBIND11_PLUGIN(libfbrw) {
    py::module m("libfbrw", "pybind11 Fuelbed reader/writer plugin");

    py::class_<FuelbedValues>(m, "FuelbedValues")
        .def(py::init<const std::string &>())
        .def("Read", &FuelbedValues::Read)
        .def("GetValue", &FuelbedValues::GetValue)
        .def("SetValue", &FuelbedValues::SetValue)
        .def("GetSpeciesValue", &FuelbedValues::GetSpeciesValue)
        .def("SetSpeciesValue", &FuelbedValues::SetSpeciesValue)
        .def("Write", (bool (FuelbedValues::*)(void)) &FuelbedValues::Write, "Write with current filename")
        .def("Write", (bool (FuelbedValues::*)(const std::string &)) &FuelbedValues::Write, "Save to new filename")
        .def("Print", &FuelbedValues::Print)
    ;
    
    py::class_<Species>(m, "Species")
        .def(py::init<const std::string &, const std::string &>())
        .def_readwrite("tsn", &Species::tsn)
        .def_readwrite("relativeCover", &Species::relativeCover)
    ;
    
    py::enum_<FBSpeciesTypes>(m, "FBSpeciesTypes")
        .value("eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_SNAGS_CLASS_2_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_SNAGS_CLASS_2_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_SNAGS_CLASS_3_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_SNAGS_CLASS_3_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_TREES_MIDSTORY_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_TREES_MIDSTORY_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_TREES_OVERSTORY_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_TREES_OVERSTORY_SPECIES_SPECIES_DESCRIPTION)
        .value("eCANOPY_TREES_UNDERSTORY_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eCANOPY_TREES_UNDERSTORY_SPECIES_SPECIES_DESCRIPTION)
        .value("eHERBACEOUS_PRIMARY_LAYER_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eHERBACEOUS_PRIMARY_LAYER_SPECIES_SPECIES_DESCRIPTION)
        .value("eHERBACEOUS_SECONDARY_LAYER_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eHERBACEOUS_SECONDARY_LAYER_SPECIES_SPECIES_DESCRIPTION)
        .value("eSHRUBS_PRIMARY_LAYER_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eSHRUBS_PRIMARY_LAYER_SPECIES_SPECIES_DESCRIPTION)
        .value("eSHRUBS_SECONDARY_LAYER_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eSHRUBS_SECONDARY_LAYER_SPECIES_SPECIES_DESCRIPTION)
        .value("eWOODY_FUEL_ROTTEN_WOOD_ALL_ROTTEN_WOOD_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eWOODY_FUEL_ROTTEN_WOOD_ALL_ROTTEN_WOOD_SPECIES_SPECIES_DESCRIPTION)
        .value("eWOODY_FUEL_SOUND_WOOD_ALL_SOUND_WOOD_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eWOODY_FUEL_SOUND_WOOD_ALL_SOUND_WOOD_SPECIES_SPECIES_DESCRIPTION)
        .value("eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_SPECIES_SPECIES_DESCRIPTION)
        .value("eWOODY_FUEL_STUMPS_ROTTEN_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eWOODY_FUEL_STUMPS_ROTTEN_SPECIES_SPECIES_DESCRIPTION)
        .value("eWOODY_FUEL_STUMPS_SOUND_SPECIES_SPECIES_DESCRIPTION", FBSpeciesTypes::eWOODY_FUEL_STUMPS_SOUND_SPECIES_SPECIES_DESCRIPTION)
    ;

    py::enum_<FBTypes>(m, "FBTypes")
        .value("eFUELBED_NUMBER", FBTypes::eFUELBED_NUMBER)
        .value("eFUELBED_NAME", FBTypes::eFUELBED_NAME)
        .value("eFUELBED_DESCRIPTION", FBTypes::eFUELBED_DESCRIPTION)
        .value("eECOREGION", FBTypes::eECOREGION)
        .value("eVEGETATION_FORM", FBTypes::eVEGETATION_FORM)
        .value("eSTRUCTURAL_CLASS", FBTypes::eSTRUCTURAL_CLASS)
        .value("eCOVER_TYPE", FBTypes::eCOVER_TYPE)
        .value("eCHANGE_AGENT", FBTypes::eCHANGE_AGENT)
        .value("eNATURAL_FIRE_REGIME", FBTypes::eNATURAL_FIRE_REGIME)
        .value("eCONDITION_CLASS", FBTypes::eCONDITION_CLASS)
        .value("eUSER_NAME", FBTypes::eUSER_NAME)
        .value("eADDRESS", FBTypes::eADDRESS)
        .value("eAFFILIATION", FBTypes::eAFFILIATION)
        .value("ePHONE", FBTypes::ePHONE)
        .value("eFILE_OWNER_EMAIL", FBTypes::eFILE_OWNER_EMAIL)
        .value("eNOTES", FBTypes::eNOTES)
        .value("eDATE_COLLECTED", FBTypes::eDATE_COLLECTED)
        .value("eFUELBED_CONFIDENCE", FBTypes::eFUELBED_CONFIDENCE)
        .value("eLITTER_ARRANGEMENT", FBTypes::eLITTER_ARRANGEMENT)
        .value("eLITTER_LITTER_TYPE_SHORT_NEEDLE_PINE_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_SHORT_NEEDLE_PINE_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_LONG_NEEDLE_PINE_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_LONG_NEEDLE_PINE_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_OTHER_CONIFER_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_OTHER_CONIFER_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_BROADLEAF_DECIDUOUS_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_BROADLEAF_DECIDUOUS_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_BROADLEAF_EVERGREEN_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_BROADLEAF_EVERGREEN_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_PALM_FROND_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_PALM_FROND_RELATIVE_COVER)
        .value("eLITTER_LITTER_TYPE_GRASS_RELATIVE_COVER", FBTypes::eLITTER_LITTER_TYPE_GRASS_RELATIVE_COVER)
        .value("eSHRUBS_NEEDLE_DRAPE_AFFECTS_FIRE_BEHAVIOR", FBTypes::eSHRUBS_NEEDLE_DRAPE_AFFECTS_FIRE_BEHAVIOR)
        .value("eCANOPY_LADDER_FUELS_MAXIMUM_HEIGHT", FBTypes::eCANOPY_LADDER_FUELS_MAXIMUM_HEIGHT)
        .value("eCANOPY_LADDER_FUELS_MINIMUM_HEIGHT", FBTypes::eCANOPY_LADDER_FUELS_MINIMUM_HEIGHT)
        .value("eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_DIAMETER", FBTypes::eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_DIAMETER)
        .value("eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_HEIGHT", FBTypes::eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_HEIGHT)
        .value("eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_STEM_DENSITY", FBTypes::eCANOPY_SNAGS_CLASS_1_ALL_OTHERS_STEM_DENSITY)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_DIAMETER", FBTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_DIAMETER)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_HEIGHT", FBTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_HEIGHT)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_HEIGHT_TO_CROWN_BASE", FBTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_HEIGHT_TO_CROWN_BASE)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_PERCENT_COVER", FBTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_PERCENT_COVER)
        .value("eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_STEM_DENSITY", FBTypes::eCANOPY_SNAGS_CLASS_1_CONIFERS_WITH_FOLIAGE_STEM_DENSITY)
        .value("eCANOPY_SNAGS_CLASS_2_DIAMETER", FBTypes::eCANOPY_SNAGS_CLASS_2_DIAMETER)
        .value("eCANOPY_SNAGS_CLASS_2_HEIGHT", FBTypes::eCANOPY_SNAGS_CLASS_2_HEIGHT)
        .value("eCANOPY_SNAGS_CLASS_2_STEM_DENSITY", FBTypes::eCANOPY_SNAGS_CLASS_2_STEM_DENSITY)
        .value("eCANOPY_SNAGS_CLASS_3_DIAMETER", FBTypes::eCANOPY_SNAGS_CLASS_3_DIAMETER)
        .value("eCANOPY_SNAGS_CLASS_3_HEIGHT", FBTypes::eCANOPY_SNAGS_CLASS_3_HEIGHT)
        .value("eCANOPY_SNAGS_CLASS_3_STEM_DENSITY", FBTypes::eCANOPY_SNAGS_CLASS_3_STEM_DENSITY)
        .value("eCANOPY_TREES_MIDSTORY_DIAMETER_AT_BREAST_HEIGHT", FBTypes::eCANOPY_TREES_MIDSTORY_DIAMETER_AT_BREAST_HEIGHT)
        .value("eCANOPY_TREES_MIDSTORY_HEIGHT", FBTypes::eCANOPY_TREES_MIDSTORY_HEIGHT)
        .value("eCANOPY_TREES_MIDSTORY_HEIGHT_TO_LIVE_CROWN", FBTypes::eCANOPY_TREES_MIDSTORY_HEIGHT_TO_LIVE_CROWN)
        .value("eCANOPY_TREES_MIDSTORY_PERCENT_COVER", FBTypes::eCANOPY_TREES_MIDSTORY_PERCENT_COVER)
        .value("eCANOPY_TREES_MIDSTORY_STEM_DENSITY", FBTypes::eCANOPY_TREES_MIDSTORY_STEM_DENSITY)
        .value("eCANOPY_TREES_OVERSTORY_DIAMETER_AT_BREAST_HEIGHT", FBTypes::eCANOPY_TREES_OVERSTORY_DIAMETER_AT_BREAST_HEIGHT)
        .value("eCANOPY_TREES_OVERSTORY_HEIGHT", FBTypes::eCANOPY_TREES_OVERSTORY_HEIGHT)
        .value("eCANOPY_TREES_OVERSTORY_HEIGHT_TO_LIVE_CROWN", FBTypes::eCANOPY_TREES_OVERSTORY_HEIGHT_TO_LIVE_CROWN)
        .value("eCANOPY_TREES_OVERSTORY_PERCENT_COVER", FBTypes::eCANOPY_TREES_OVERSTORY_PERCENT_COVER)
        .value("eCANOPY_TREES_OVERSTORY_STEM_DENSITY", FBTypes::eCANOPY_TREES_OVERSTORY_STEM_DENSITY)
        .value("eCANOPY_TREES_TOTAL_PERCENT_COVER", FBTypes::eCANOPY_TREES_TOTAL_PERCENT_COVER)
        .value("eCANOPY_TREES_UNDERSTORY_DIAMETER_AT_BREAST_HEIGHT", FBTypes::eCANOPY_TREES_UNDERSTORY_DIAMETER_AT_BREAST_HEIGHT)
        .value("eCANOPY_TREES_UNDERSTORY_HEIGHT", FBTypes::eCANOPY_TREES_UNDERSTORY_HEIGHT)
        .value("eCANOPY_TREES_UNDERSTORY_HEIGHT_TO_LIVE_CROWN", FBTypes::eCANOPY_TREES_UNDERSTORY_HEIGHT_TO_LIVE_CROWN)
        .value("eCANOPY_TREES_UNDERSTORY_PERCENT_COVER", FBTypes::eCANOPY_TREES_UNDERSTORY_PERCENT_COVER)
        .value("eCANOPY_TREES_UNDERSTORY_STEM_DENSITY", FBTypes::eCANOPY_TREES_UNDERSTORY_STEM_DENSITY)
        .value("eGROUND_FUEL_BASAL_ACCUMULATION_DEPTH", FBTypes::eGROUND_FUEL_BASAL_ACCUMULATION_DEPTH)
        .value("eGROUND_FUEL_BASAL_ACCUMULATION_NUMBER_PER_UNIT_AREA", FBTypes::eGROUND_FUEL_BASAL_ACCUMULATION_NUMBER_PER_UNIT_AREA)
        .value("eGROUND_FUEL_BASAL_ACCUMULATION_RADIUS", FBTypes::eGROUND_FUEL_BASAL_ACCUMULATION_RADIUS)
        .value("eGROUND_FUEL_BASAL_ACCUMULATION_LOADING", FBTypes::eGROUND_FUEL_BASAL_ACCUMULATION_LOADING)
        .value("eGROUND_FUEL_DUFF_LOWER_DEPTH", FBTypes::eGROUND_FUEL_DUFF_LOWER_DEPTH)
        .value("eGROUND_FUEL_DUFF_LOWER_PERCENT_COVER", FBTypes::eGROUND_FUEL_DUFF_LOWER_PERCENT_COVER)
        .value("eGROUND_FUEL_DUFF_LOWER_LOADING", FBTypes::eGROUND_FUEL_DUFF_LOWER_LOADING)
        .value("eGROUND_FUEL_DUFF_UPPER_DEPTH", FBTypes::eGROUND_FUEL_DUFF_UPPER_DEPTH)
        .value("eGROUND_FUEL_DUFF_UPPER_PERCENT_COVER", FBTypes::eGROUND_FUEL_DUFF_UPPER_PERCENT_COVER)
        .value("eGROUND_FUEL_DUFF_UPPER_LOADING", FBTypes::eGROUND_FUEL_DUFF_UPPER_LOADING)
        .value("eGROUND_FUEL_SQUIRREL_MIDDENS_DEPTH", FBTypes::eGROUND_FUEL_SQUIRREL_MIDDENS_DEPTH)
        .value("eGROUND_FUEL_SQUIRREL_MIDDENS_NUMBER_PER_UNIT_AREA", FBTypes::eGROUND_FUEL_SQUIRREL_MIDDENS_NUMBER_PER_UNIT_AREA)
        .value("eGROUND_FUEL_SQUIRREL_MIDDENS_RADIUS", FBTypes::eGROUND_FUEL_SQUIRREL_MIDDENS_RADIUS)
        .value("eGROUND_FUEL_SQUIRREL_MIDDENS_LOADING", FBTypes::eGROUND_FUEL_SQUIRREL_MIDDENS_LOADING)
        .value("eHERBACEOUS_PRIMARY_LAYER_HEIGHT", FBTypes::eHERBACEOUS_PRIMARY_LAYER_HEIGHT)
        .value("eHERBACEOUS_PRIMARY_LAYER_LOADING", FBTypes::eHERBACEOUS_PRIMARY_LAYER_LOADING)
        .value("eHERBACEOUS_PRIMARY_LAYER_PERCENT_COVER", FBTypes::eHERBACEOUS_PRIMARY_LAYER_PERCENT_COVER)
        .value("eHERBACEOUS_PRIMARY_LAYER_PERCENT_LIVE", FBTypes::eHERBACEOUS_PRIMARY_LAYER_PERCENT_LIVE)
        .value("eHERBACEOUS_SECONDARY_LAYER_HEIGHT", FBTypes::eHERBACEOUS_SECONDARY_LAYER_HEIGHT)
        .value("eHERBACEOUS_SECONDARY_LAYER_LOADING", FBTypes::eHERBACEOUS_SECONDARY_LAYER_LOADING)
        .value("eHERBACEOUS_SECONDARY_LAYER_PERCENT_COVER", FBTypes::eHERBACEOUS_SECONDARY_LAYER_PERCENT_COVER)
        .value("eHERBACEOUS_SECONDARY_LAYER_PERCENT_LIVE", FBTypes::eHERBACEOUS_SECONDARY_LAYER_PERCENT_LIVE)
        .value("eMOSS_LICHEN_LITTER_GROUND_LICHEN_DEPTH", FBTypes::eMOSS_LICHEN_LITTER_GROUND_LICHEN_DEPTH)
        .value("eMOSS_LICHEN_LITTER_GROUND_LICHEN_PERCENT_COVER", FBTypes::eMOSS_LICHEN_LITTER_GROUND_LICHEN_PERCENT_COVER)
        .value("eMOSS_LICHEN_LITTER_GROUND_LICHEN_LOADING", FBTypes::eMOSS_LICHEN_LITTER_GROUND_LICHEN_LOADING)
        .value("eMOSS_LICHEN_LITTER_LITTER_DEPTH", FBTypes::eMOSS_LICHEN_LITTER_LITTER_DEPTH)
        .value("eMOSS_LICHEN_LITTER_LITTER_PERCENT_COVER", FBTypes::eMOSS_LICHEN_LITTER_LITTER_PERCENT_COVER)
        .value("eMOSS_LICHEN_LITTER_LITTER_LOADING", FBTypes::eMOSS_LICHEN_LITTER_LITTER_LOADING)
        .value("eMOSS_LICHEN_LITTER_MOSS_DEPTH", FBTypes::eMOSS_LICHEN_LITTER_MOSS_DEPTH)
        .value("eMOSS_LICHEN_LITTER_MOSS_PERCENT_COVER", FBTypes::eMOSS_LICHEN_LITTER_MOSS_PERCENT_COVER)
        .value("eMOSS_LICHEN_LITTER_MOSS_LOADING", FBTypes::eMOSS_LICHEN_LITTER_MOSS_LOADING)
        .value("eSHRUBS_PRIMARY_LAYER_HEIGHT", FBTypes::eSHRUBS_PRIMARY_LAYER_HEIGHT)
        .value("eSHRUBS_PRIMARY_LAYER_PERCENT_COVER", FBTypes::eSHRUBS_PRIMARY_LAYER_PERCENT_COVER)
        .value("eSHRUBS_PRIMARY_LAYER_PERCENT_LIVE", FBTypes::eSHRUBS_PRIMARY_LAYER_PERCENT_LIVE)
        .value("eSHRUBS_PRIMARY_LAYER_LOADING", FBTypes::eSHRUBS_PRIMARY_LAYER_LOADING)
        .value("eSHRUBS_SECONDARY_LAYER_HEIGHT", FBTypes::eSHRUBS_SECONDARY_LAYER_HEIGHT)
        .value("eSHRUBS_SECONDARY_LAYER_PERCENT_COVER", FBTypes::eSHRUBS_SECONDARY_LAYER_PERCENT_COVER)
        .value("eSHRUBS_SECONDARY_LAYER_PERCENT_LIVE", FBTypes::eSHRUBS_SECONDARY_LAYER_PERCENT_LIVE)
        .value("eSHRUBS_SECONDARY_LAYER_LOADING", FBTypes::eSHRUBS_SECONDARY_LAYER_LOADING)
        .value("eWOODY_FUEL_ALL_DOWNED_WOODY_FUEL_DEPTH", FBTypes::eWOODY_FUEL_ALL_DOWNED_WOODY_FUEL_DEPTH)
        .value("eWOODY_FUEL_ALL_DOWNED_WOODY_FUEL_TOTAL_PERCENT_COVER", FBTypes::eWOODY_FUEL_ALL_DOWNED_WOODY_FUEL_TOTAL_PERCENT_COVER)
        .value("eWOODY_FUEL_PILES_CLEAN_LOADING", FBTypes::eWOODY_FUEL_PILES_CLEAN_LOADING)
        .value("eWOODY_FUEL_PILES_DIRTY_LOADING", FBTypes::eWOODY_FUEL_PILES_DIRTY_LOADING)
        .value("eWOODY_FUEL_PILES_VERYDIRTY_LOADING", FBTypes::eWOODY_FUEL_PILES_VERYDIRTY_LOADING)
        .value("eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_GREATER_THAN_TWENTY_INCHES", FBTypes::eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_GREATER_THAN_TWENTY_INCHES)
        .value("eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_NINE_TO_TWENTY_INCHES", FBTypes::eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_NINE_TO_TWENTY_INCHES)
        .value("eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_THREE_TO_NINE_INCHES", FBTypes::eWOODY_FUEL_ROTTEN_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_THREE_TO_NINE_INCHES)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_GREATER_THAN_TWENTY_INCHES", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_GREATER_THAN_TWENTY_INCHES)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_NINE_TO_TWENTY_INCHES", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_NINE_TO_TWENTY_INCHES)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_THREE_TO_NINE_INCHES", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_GREATER_THAN_THREE_INCHES_THREE_TO_NINE_INCHES)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_ONE_TO_THREE_INCHES", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_ONE_TO_THREE_INCHES)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_QUARTER_INCH_TO_ONE_INCH", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_QUARTER_INCH_TO_ONE_INCH)
        .value("eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_ZERO_TO_QUARTER_INCH", FBTypes::eWOODY_FUEL_SOUND_WOOD_LOADINGS_ZERO_TO_THREE_INCHES_ZERO_TO_QUARTER_INCH)
        .value("eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_DIAMETER", FBTypes::eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_DIAMETER)
        .value("eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_HEIGHT", FBTypes::eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_HEIGHT)
        .value("eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_STEM_DENSITY", FBTypes::eWOODY_FUEL_STUMPS_LIGHTERED_PITCHY_STEM_DENSITY)
        .value("eWOODY_FUEL_STUMPS_ROTTEN_DIAMETER", FBTypes::eWOODY_FUEL_STUMPS_ROTTEN_DIAMETER)
        .value("eWOODY_FUEL_STUMPS_ROTTEN_HEIGHT", FBTypes::eWOODY_FUEL_STUMPS_ROTTEN_HEIGHT)
        .value("eWOODY_FUEL_STUMPS_ROTTEN_STEM_DENSITY", FBTypes::eWOODY_FUEL_STUMPS_ROTTEN_STEM_DENSITY)
        .value("eWOODY_FUEL_STUMPS_SOUND_DIAMETER", FBTypes::eWOODY_FUEL_STUMPS_SOUND_DIAMETER)
        .value("eWOODY_FUEL_STUMPS_SOUND_HEIGHT", FBTypes::eWOODY_FUEL_STUMPS_SOUND_HEIGHT)
        .value("eWOODY_FUEL_STUMPS_SOUND_STEM_DENSITY", FBTypes::eWOODY_FUEL_STUMPS_SOUND_STEM_DENSITY)
    ;

    return m.ptr();
}
